#!/bin/bash
VMXFILE=Ubuntu7.10.vmx
VMXPATH="/var/lib/vmware/Virtual Machines/Ubuntu7.10"

if ! [ -e "${VMXPATH}/${VMXFILE}" ] ; then
	echo "${VMXFILE} file does not exists!"
	exit 1
fi
vmrun revertToSnapshot "${VMXPATH}/${VMXFILE}"
